### ISSUE TITLE
Can't install with either NPX or Yarn

### ISSUE THREAD

**Issue by ViktorJT** [pmndrs/react-three-next#112]
I followed installation guide with both NPX & Yarn, however both fail.

**Yarn (3.3.1)** installation using `yarn create r3f-app next my-app` fails to create project and returns this error:
```
Error: create-r3f-app tried to access semver, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: semver
Required by: create-r3f-app@npm:1.5.8 (via /Users/viktor.jensen-torp/.yarn/berry/cache/create-r3f-app-npm-1.5.8-293b86f139-8.zip/node_modules/create-r3f-app/lib/utils/)

Require stack:
- /Users/viktor.jensen-torp/.yarn/berry/cache/create-r3f-app-npm-1.5.8-293b86f139-8.zip/node_modules/create-r3f-app/lib/utils/check-for-update.js
- /Users/viktor.jensen-torp/.yarn/berry/cache/create-r3f-app-npm-1.5.8-293b86f139-8.zip/node_modules/create-r3f-app/lib/index.js
- /Users/viktor.jensen-torp/.yarn/berry/cache/create-r3f-app-npm-1.5.8-293b86f139-8.zip/node_modules/create-r3f-app/bin/create-r3f-app
    at require$$0.Module._resolveFilename (/private/var/folders/0r/m9b8svds5vz681mdr_9jc_4c0000gn/T/xfs-f1e65f39/dlx-44598/.pnp.cjs:12458:13)
    at require$$0.Module._load (/private/var/folders/0r/m9b8svds5vz681mdr_9jc_4c0000gn/T/xfs-f1e65f39/dlx-44598/.pnp.cjs:12308:42)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/viktor.jensen-torp/.yarn/berry/cache/create-r3f-app-npm-1.5.8-293b86f139-8.zip/node_modules/create-r3f-app/lib/utils/check-for-update.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at require$$0.Module._extensions..js (/private/var/folders/0r/m9b8svds5vz681mdr_9jc_4c0000gn/T/xfs-f1e65f39/dlx-44598/.pnp.cjs:12502:33)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at require$$0.Module._load (/private/var/folders/0r/m9b8svds5vz681mdr_9jc_4c0000gn/T/xfs-f1e65f39/dlx-44598/.pnp.cjs:12339:14)

Node.js v18.9.0
```

NPX (9.2.0, Node version 18.9.0) installation using `npx create-r3f-app next my-app` also fails to create project, and returns the text:
```
  —— New update available, run the following yarn create r3f-app <next> my-app <tailwind|styled>? -ts
```
And then quits without errors

**Comment by ViktorJT** [comment]
Am able to install with NPX using older node version (16.17.0), however getting this issue #89 when trying to npm install
