### ISSUE TITLE
Model won't load when auto-generated with gltfjsx

### ISSUE THREAD

**Issue by harisraharjo** [pmndrs/react-three-next#49]
I downloaded the model from sketchfab (.gltf) and converted it into an r3f component using gltfjsx. The model couldn't be loaded even though I tried to package it into a single .glb file using https: https://sbtron.github.io/makeglb/.

Repo: https://github.com/harisraharjo/r3f-next-error

**Comment by Entryist** [comment]
This is the error, and I get the same error when attempting to pull in a GLB like from the [three graces example](https://codesandbox.io/s/the-three-graces-0n9it?file=/package.json).
```
The above error occurred in the <ForwardRef(Canvas)> component:

    at Canvas (webpack-internal:///./node_modules/@react-three/fiber/dist/react-three-fiber.esm.js:1519:3)
    at LCanvas (webpack-internal:///./src/components/layout/canvas.jsx:56:23)
    at ForwardPropsToR3fComponent (webpack-internal:///./src/pages/_app.jsx:58:20)
    at App (webpack-internal:///./src/pages/_app.jsx:102:25)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:195:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:683:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:819:25)
```

**Comment by anudit** [comment]
Happens in my codebase too with `useGLTF()`

**Comment by nickmcmillan** [comment]
Same issue here.

The error message doesn't really help much but I think it could be a suspense issue. Wrapping the model component with Suspense and adding the `r3f` prop seemed to work for me, eg;

```
<Suspense fallback={null} r3f>
  <Model />
</Suspense>
```

The `r3f` prop is what this library uses to determine whether to forward the component to the dom or to the canvas. Typescript doesn't like the prop being added to Suspense though.

**Comment by anudit** [comment]
@nickmcmillan Yup that's the way to go.

**Comment by RenaudRohlinger** [comment]
Hey guys! The fact the error is not getting handle is because the starter is using dynamic component imports which is very nice for a fast render of the DOM but can have some issues such as this one.

I can only recommend importing statically to prevent this:
`import Box from '@/components/canvas/Box'`

I think it should be better to let the developer choose and go back to static import. That's not very the best performance-wise as it will add a big payload with all the r3f / threejs stack.

What do you guys think?

**Comment by RenaudRohlinger** [comment]
Thanks, everyone! 
I updated the architecture of the pages and also added a warning for the dynamic components.

**Comment by richardeakin** [comment]
Apologies if this is the wrong place but I've run into an issue after trying to switch to the `import LCanvas from '@/components/layout/canvas';` way in order to get debuggable error logs. Now I'm seeing this, which I don't understand..

```
event - compiled successfully in 500 ms (1109 modules)
G:\projects\buck\bonds-sheets\bonds-sheets-ar\app\node_modules\@react-three\drei\native\index.js:1
export { Billboard } from '../core/Billboard.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.@react-three/drei/native (G:\projects\buck\bonds-sheets\bonds-sheets-ar\app\.next\server\pages\_app.js:142:18)
    at __webpack_require__ (G:\projects\buck\bonds-sheets\bonds-sheets-ar\app\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/components/8thwall/DevHelpers.jsx:10:82)
    at Object../src/components/8thwall/DevHelpers.jsx (G:\projects\buck\bonds-sheets\bonds-sheets-ar\app\.next\server\pages\_app.js:44:1)
    at __webpack_require__ (G:\projects\buck\bonds-sheets\bonds-sheets-ar\app\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/components/layout/canvas.jsx:17:77)
    at Object../src/components/layout/canvas.jsx (G:\projects\buck\bonds-sheets\bonds-sheets-ar\app\.next\server\pages\_app.js:66:1)
    at __webpack_require__ (G:\projects\buck\bonds-sheets\bonds-sheets-ar\app\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/_app.jsx:12:83)
```

I've only tried getting rid of all the `dynamic()` import calls and commented out all other changes.. does this error mean anything to anyone?

Thanks for the help,
Rich
