### ISSUE TITLE
Trouble upgrading to next 12

### ISSUE THREAD

**Issue by chasedavis** [pmndrs/react-three-next#60]
When I upgrade to next 12 I encounter the following error on build:

```
event - compiled successfully in 476 ms (871 modules)
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at _app.jsx:42.
    at ForwardPropsToR3fComponent (webpack-internal:///./src/pages/_app.jsx:67:3)
    at UserContextProvider (webpack-internal:///./src/utils/useUser.js:28:54)
    at App (webpack-internal:///./src/pages/_app.jsx:108:3)
    at StyleRegistry (/Users/chasedavis/Documents/meshbg/node_modules/styled-jsx/dist/stylesheet-registry.js:231:34)
    at AppContainer (/Users/chasedavis/Documents/meshbg/node_modules/next/dist/server/render.js:325:29)
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at ReactDOMServerRenderer.render (/Users/chasedavis/Documents/meshbg/node_modules/react-dom/cjs/react-dom-server.node.development.js:4053:17)
    at ReactDOMServerRenderer.read (/Users/chasedavis/Documents/meshbg/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/Users/chasedavis/Documents/meshbg/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/Users/chasedavis/Documents/meshbg/node_modules/next/dist/server/render.js:621:45)
    at Object.defaultGetInitialProps (/Users/chasedavis/Documents/meshbg/node_modules/next/dist/server/render.js:301:51)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:187:16)
    at Object.loadGetInitialProps (/Users/chasedavis/Documents/meshbg/node_modules/next/dist/shared/lib/utils.js:69:29)
    at renderDocument (/Users/chasedavis/Documents/meshbg/node_modules/next/dist/server/render.js:634:48)
    at Object.renderToHTML (/Users/chasedavis/Documents/meshbg/node_modules/next/dist/server/render.js:673:34)
    at async doRender (/Users/chasedavis/Documents/meshbg/node_modules/next/dist/server/next-server.js:1389:38)
    at async /Users/chasedavis/Documents/meshbg/node_modules/next/dist/server/next-server.js:1484:28
    at async /Users/chasedavis/Documents/meshbg/node_modules/next/dist/server/response-cache.js:63:36
```

My naive assumption is that the next.config.js needs an update, as it seems like under the hood there are some curly braces missing when trying to load the `export default App` from _app.jsx

EDIT:

It looks like I may be experiencing [this issue](https://stackoverflow.com/questions/69748491/why-does-nextjs-react-say-you-likely-forgot-to-export-your-component-from-the-f) and I also receive the following error in dev tool
<img width="508" alt="Screen Shot 2021-11-05 at 3 05 14 PM" src="https://user-images.githubusercontent.com/10068755/140565003-151a5215-aba8-431b-995a-313ecc086f24.png">
s

**Comment by RenaudRohlinger** [comment]
@chasedavis Hi! Sorry for the delay I was pretty busy recently, I added update that should now support the v12!
